### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by eband** [JosephM101/Force-Windows-11-Install#10]
What are the system requirements for using this tool?

For example, can I just use a computer with a Windows 7 Ultimate 32-bit before operating this?

**Comment by JosephM101** [comment]
Unfortunately, no. I'd consider Windows 10 21H2 to be the minimum for the tool, and it has to be 64-bit.

As for a specific list of requirements, you need:
- A 64-bit system (Windows 11 does not support 32-bit systems)
- An already-installed 64-bit version of Windows (if you want to upgrade without wiping your current install/data)
- Windows 10 21H2 or later for running the tool

I hope this helps!
