### ISSUE TITLE
22H2 Error input string was not in a correct format

### ISSUE THREAD

**Issue by updawg** [JosephM101/Force-Windows-11-Install#13]
boot.wim patched. Took 00:00:37
Cannot convert argument "bytes", with value: "force-windows-11-install", for "WriteAllBytes" to type "System.Byte[]":
"Cannot convert value "force-windows-11-install" to type "System.Byte[]". Error: "Cannot convert value
"force-windows-11-install" to type "System.Byte". Error: "Input string was not in a correct format."""
At C:\Users\****\Downloads\Force-Windows-11-Install-main\Win11-TPM-RegBypass.ps1:835 char:5
+     [System.IO.File]::WriteAllBytes($sb_mark, $CONTENT)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

**Comment by JosephM101** [comment]
Thank you for bringing this to my attention. This is not a mission-critical bug, so I will just comment out the code that requires it.

**Comment by JosephM101** [comment]
I have just made and committed the change. Please go ahead and retry the operation you were attempting before.
