### ISSUE TITLE
ISO Image not found

### ISSUE THREAD

**Issue by 2010MistubishiLancerEvolutionX** [JosephM101/Force-Windows-11-Install#14]
![Screenshot (1)](https://user-images.githubusercontent.com/83099780/211186646-a2c0f660-8e90-4ab1-ad59-f116c21cefe3.png)

**Comment by nyamwaro1** [comment]
also am facing the same issue kindly someone to help

**Comment by JosephM101** [comment]
The path names need to be fully qualified. For example, "`windows.iso`" would become "`C:/Users/someuser/Downloads/windows.iso`" (or wherever you have the file stored)

Please also keep in mind that filenames are case-sensitive.

Hope this helps!
