### ISSUE TITLE
error with Win11-ImageBuilder.ps1

### ISSUE THREAD

**Issue by system-something** [JosephM101/Force-Windows-11-Install#15]
Error in:

PS C:\Users\Herb\Desktop\Force-Windows-11-Install-main> .\Win11-ImageBuilder.ps1 -Source "Win.iso" -Destination "winbk.iso"

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\Herb\Desktop\Force-Windows-11-Install-main\Win11-ImageBuilder.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
C:\Users\Herb\Desktop\Force-Windows-11-Install-main\Win11-ImageBuilder.ps1 : A parameter cannot be found that matches
parameter name 'Source'.
At line:1 char:26
+ .\Win11-ImageBuilder.ps1 -Source "Win.iso" -Destination "winbk.iso"
+                          ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Win11-ImageBuilder.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Win11-ImageBuilder.ps1

**Comment by JosephM101** [comment]
The syntax you're using only applies to the "Win11-TPM-RegBypass.ps1" script. Based on that syntax, this is the command you want:
`.\Win11-ImageBuilder.ps1 -Source "Win.iso" -Destination "winbk.iso"`

If you're looking to use the ImageBuilder script, you may refer to its documentation in the 'docs' folder of the repository. **Please keep in mind that the ImageBuilder script you're trying to use is deprecated, and will be moved in the future.**

**Comment by JosephM101** [comment]
The syntax you're using only applies to the "Win11-TPM-RegBypass.ps1" script. Based on that syntax, this is the command you want:
`.\Win11-TPM-RegBypass.ps1 -Source "Win.iso" -Destination "winbk.iso"`

If you're looking to use the ImageBuilder script, you may refer to its documentation in the 'docs' folder of the repository. **Please keep in mind that the ImageBuilder script uses an outdated method and is therefore deprecated, and will be (re)moved in the future.**

**Comment by JosephM101** [comment]
Glad I could help! Seeing as how it seems like things are working now on your end, I will close this issue as "solved".
Enjoy!
