### ISSUE TITLE
Love this tool!

### ISSUE THREAD

**Issue by dillfrescott** [JosephM101/Force-Windows-11-Install#22]
But you can just use Rufus now, and it gives a little menu before you burn the iso to bypass the requirements and stuff.

![Screenshot 2024-03-28 022620](https://github.com/JosephM101/Force-Windows-11-Install/assets/56714680/7bd23d45-6b0c-49d3-be06-2ea3e9b6f7f9)

**Comment by JosephM101** [comment]
Thank you, I'm aware. It's one of the reasons why I'm no longer updating this script.

**Comment by dillfrescott** [comment]
Agreed
