### ISSUE TITLE
Lenovo T510 Win10 Pro Version 22H2 - The new ISO does not bypass TPM check

### ISSUE THREAD

**Issue by Guy202412** [JosephM101/Force-Windows-11-Install#23]
Hello, it looks like the script has not yet been updated for newer Windows builds. (Windows 11 Compatibility Check Bypass Tool Version 1.4). the new ISO does not bypass TPM check. 

[Lenovo T510 Patch execution 20241223.txt](https://github.com/user-attachments/files/18231852/Lenovo.T510.Patch.execution.20241223.txt)

![ScriptExecution 2](https://github.com/user-attachments/assets/6f6ce214-f335-4b7c-aa70-47a4dd4b66eb)

**Comment by JosephM101** [comment]
I'm really sorry to inconvenience you, but I've stopped updating this repository. I simply don't have the time, and there are much better open-source free tools out there such as Rufus for creating patched bootable drives, and [Flyby11](https://github.com/builtbybel/Flyby11) for setting up your PC for in-place upgrades. Flyby11 is what you want.
