### ISSUE TITLE
Still get "TPM 2.0" requirement error 

### ISSUE THREAD

**Issue by harnoorsaini** [JosephM101/Force-Windows-11-Install#3]
When I mount the newly created ISO (original ISO I obtained from Microsoft official site) and run setup.exe, I still run into the same error...

**Comment by harnoorsaini** [comment]
Yep

**Comment by harnoorsaini** [comment]
Hi, so some errors: first it says the script only runs on windows. I hacked it with "$IsWindows = $true", then I get a "This will only run on 64-bit devices" , there was a rogue "$Is64BitSystem = $false" @ line 111. So changed that, then it ran with a warning: "Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.". I then restarted, but for the same error again...

**Comment by JosephM101** [comment]
I appreciate you telling me what some of the problems were. I just realized that there were debug/testing flags left behind that I forgot to revert, and they were causing problems. I'm still trying to figure out what's wrong with the patching routine. I'll let you know what I figure out.

**Comment by JosephM101** [comment]
Excellent! The patch should force upgrades from Windows Update to bypass the checks as well. I don't know if it would need to be reapplied again, but at least we know it works!

**Comment by JosephM101** [comment]
I will do further testing once I get home. Thanks for communicating with me!

**Comment by harnoorsaini** [comment]
OK, so I am in! So far so good, I will install updates and see if it complains.

**Comment by JosephM101** [comment]
Sounds good! Since everything's working so far, I'm going to close this issue. Just post again if anything goes wrong.

Thank you for helping out!
